### ISSUE TITLE
"SyntaxError: Unexpected token '{' (body:line 3)" while trying to send command

### ISSUE THREAD

**Issue by mano-30** [sisodiakaran/node-red-contrib-atomberg#1]
I tried the test function as mentioned in the example. But I am getting the error mentioned in the title. This is the message I passed in the function block  before I passed it to the send-command block. 
`msg.payload = {
  device_id: "ffrvsrv123s",
  {
    "speed": 6
  }
};
return msg;`

**Comment by hawk-aj** [comment]
the message payload should be as follows -
```msg.payload = { "device_id": "6867258b9d78", "command": { "timer": 0 } }```

referring the request body from the api documentation here - 
https://developer.atomberg-iot.com/#post-/v1/send_command

**Comment by sisodiakaran** [comment]
@mano-30 I have updated the example json file. Can you please verify if it is working now. @hawk-aj thanks for clarification.
